// Auto-generated by build-eiken-js.mjs
window.EIKEN_PAGES = [
  {
    "id": "eiken_4-5",
    "label": "4,5級",
    "hint": "中学英語の土台。ここが固まらないと3級は無理。",
    "href": "eiken_loader.html?page=eiken_4-5"
  },
  {
    "id": "eiken_3",
    "label": "3級",
    "hint": "共通テストは4割程度だ。",
    "href": "eiken_loader.html?page=eiken_3"
  },
  {
    "id": "eiken_pre2",
    "label": "準2級",
    "hint": "共通テストは5割程度だ。",
    "href": "eiken_loader.html?page=eiken_pre2"
  },
  {
    "id": "eiken_2",
    "label": "2級",
    "hint": "上振れたとしても共通テストは7割程度だ。MARCH一般のスタートライン。",
    "href": "eiken_loader.html?page=eiken_2"
  },
  {
    "id": "eiken_pre1",
    "label": "準1級",
    "hint": "共通テスト8割以上は固い。旧帝、早慶狙うなら最低でもここ。",
    "href": "eiken_loader.html?page=eiken_pre1"
  }
];
